### ISSUE TITLE
[Need info] GPUs limitations and requiremets

### ISSUE THREAD

**Issue by air55555** [satoshi-ikehata/SDM-UniPS-CVPR2023#6]
Satoshi , any computation requirements for particular inputs? Lets say you need 16 gb GPU for 2k X 2k pix 10 imgs, but you can make 50 imgs on downscaled to 1k X 1k pix imgs. And you need 24 gb for 2k X 2kX 50 imgs .

Does anybody have empirical requirements for various input?
What about time frame for processing imgs ?

**Comment by satoshi-ikehata** [comment]
While it is theoretically possible to predict the specific GPU memory consumption in advance, it is difficult to make a definitive statement due to the large number of related parameters involved, and I have not personally evaluated it before.

As for solutions to memory insufficiency, if the encoder is already running out of memory, you can either reduce the number of images or their resolutions or decrease the block size in "scalable" option (the default block size is 512x512, so theoretically reducing it to 256x256 (encoder input size) would result in a 1/4 reduction in memory usage).

If only the decoder is experiencing insufficient memory, you can reduce the number of samples in pixel-sampling Transformer, which will decrease memory usage in proportion to that reduction.

However, regardless of the approach taken, it involves a trade-off with accuracy, so it is generally recommended to run the model with the maximum amount of information possible within your available environment.

**Comment by air55555** [comment]
Satoshi, thanks. But what about details? How can I know where is the bottleneck? Encoder or Transformer? Is there any logging?

**Comment by satoshi-ikehata** [comment]
The straightfarward way  may be to stop the code at the end of the encoder and investigate the GPU  process using task manager or any other monitoring tools.

**Comment by air55555** [comment]
Satoshi, thanks, will investigate by myself on 3060 gpu

**Comment by air55555** [comment]
Satoshi, thanks, will investigate by myself on 3060 gpu
